# 문자와 문자열

In [3]:
#27866번

S = input()
i = int(input())

print(S)
print(i)
print(S[i-1])

Baekjoon
4
k


In [4]:
#2743번

S = input()


print(S)
print(len(S))



Pulljima
8


In [5]:
#9086번


T = int(input())

for i in range(T):
    S = input()
    print(S[0], S[-1], sep='')



AF
00
AB


In [10]:
#11654

S = input()
print(ord(S))

48


In [14]:
#11720 

N = int(input())
num = input() #정수는 인덱스 처리 불가
total_sum = 0 

for i in range(N):
    total_sum += int(num[i])
print(total_sum)
    

15


In [39]:
#10809

s = input()
x = 'abcdefghijklmnopqrstuvwxyz'

for char in x:
    print(s.find(char) , end=" ")




1 0 -1 -1 2 -1 -1 -1 -1 4 3 -1 -1 7 5 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 

In [53]:
#2675

num = int(input())

for i in range(num):
    R = int(input())
    S = input()
    for s in range(len(S)):
        print(S[s]*R , end="")
    print()

AAABBBCCC
/////HHHHHTTTTTPPPPP


In [60]:
#1152
# The Curious Case of Benjamin Button

S = input()
num_count = 1

for i in S:
    if ord(i) == 32:
        num_count +=1 
print(num_count)
    

6


In [66]:
#2908 

num1 = input()
num2 = input()

max(int(num1[::-1]),int(num2[::-1]))


437

# 해설 봐도 모르겠는 문제들

In [85]:
#5622

x = '000000abcdefghijklmnopqrstuvwxyz'


s = input()
second = 0 
for char in s:
   second += x.find(char)//3
print(second)

11


In [1]:
#11718 

while True:
    try:
        s = input()
        print(s)
    except EOFError:
        break


Hello
Baekjoon
Online Judge



In [6]:
# 기존 코드 줄이기

score = input()

if score.isdecimal():
    score = int(score)

    if 0 <= score <= 100:
        if score >= 90:     # score < 100 and score > 90
            print('A')
        elif score >= 80:   # score < 90 and score >= 80
            print('B')
        elif score >= 70:
            print('C')
        elif score >= 60:
            print('D')
        else:
            print('F')

else:
    print('입력 오류')

입력 오류


In [4]:
try:
    score = int(input())
    assert 0 <= int(score) <= 100
    if score >= 90:     # score < 100 and score > 90
        print('A')
    elif score >= 80:   # score < 90 and score >= 80
        print('B')
    elif score >= 70:
        print('C')
    elif score >= 60:
        print('D')
    else:
        print('F')
except TypeError as e:
    print('입력 오류')
except Exception as e:
    print('입력 오류')


입력 오류


# 숙제 

In [30]:
# 10807
N = int(input())
S = input() 
V = int(input())
n_list = []
for s in S:
    if s != " ":
        n_list.append(int(s))

print(n_list.count(V))

3


In [57]:
#10811 
n, m = map(int, input().split())

baskets = list(range(1, n+1))

for i in range(m):
    i, j = map(int , input().split())
    baskets[i-1:j] = baskets[i-1:j][::-1] #이렇게도 쓰나요 

    

print(" ".join(map(str, baskets)))

3 4 1 2 5


In [53]:
sum(score_list)/len(score_list)

75.0

In [42]:
list

[50.0, 100, 75.0]

In [166]:
#학생이 한반에 100명이 있음. 시험을 봤는데 성적이 1~100등까지 나왔음
#20등까지는 1을 주고 싶고 , 21~40는 2를 주고 , 81~100은 5를 받게 하는 프로그램 작성하기 
#그거를 if , for 문 없이  

import numpy as np 
ranks = np.arange(1,101)
np.where(ranks <= 20 , 1, np.where(ranks <= 40, 2 , np.where(ranks <= 60, 3 , np.where(ranks <= 80 , 4 , np.where(ranks <= 100, 5, 5)))))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5])

In [160]:
ranks = np.arange(1,101)

np.where(ranks <= 20 , 1)

ValueError: either both or neither of x and y should be given

In [153]:
import numpy as np
ranks = np.arange(0,10)
np.where(ranks <= 20)

In [25]:
np.arange(0.1 , 10)
np.arange(0.1, 10, dtype = np.int32)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [26]:
np.linspace(2,3, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [30]:
np.linspace(2,3, num=5)
np.linspace(2,3, num=5 , endpoint=False)

np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [33]:
np.zeros([10,2])

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.ones(5)
np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
x = np.tril([[1,2,3], [4,5,6], [7,8,9]
, [10,11,12]])


In [45]:
np.random.normal(size=(5, 5))

array([[ 0.21746426, -0.84963757, -0.26254434, -0.00590851,  0.49220319],
       [ 0.59263172, -1.09590223,  0.89973174, -0.27113673, -0.66385446],
       [ 0.29895277,  1.00966713,  0.54864052, -0.22831002,  0.66892061],
       [ 1.48028521, -3.09034405, -0.03612846,  0.46346022, -0.33058318],
       [ 0.50942772, -0.70088255,  0.44712111,  1.34371088, -2.72672172]])

In [49]:
np.random.normal(size=(5, 5))* np.triu(np.full((5, 5), 1))

array([[ 1.10220198,  0.24581713, -0.13215035, -0.22587907,  0.51003579],
       [ 0.        , -0.32029276, -0.93294509, -0.40852619,  0.28222956],
       [ 0.        , -0.        ,  0.36818759,  0.39178041,  1.37311818],
       [ 0.        , -0.        , -0.        , -1.17884412, -1.08152375],
       [-0.        , -0.        , -0.        , -0.        , -0.84146537]])

In [52]:
np.random.random(size=(2,3))

array([[0.24820351, 0.79954837, 0.53015102],
       [0.53071589, 0.60004003, 0.27795895]])

In [54]:
np.random.randint(0,10 , size=(5,2))

array([[0, 8],
       [9, 1],
       [2, 2],
       [3, 6],
       [4, 0]])

In [56]:
np.random.normal(0,1, size=(5,2))

array([[-1.18061031, -0.51524358],
       [-2.0108183 ,  0.29789554],
       [-0.54466047, -2.1944578 ],
       [-0.79346592, -1.97490039],
       [-0.05287805,  0.33050731]])

In [58]:
np.random.randint(1,46,size=6)

array([33, 36, 41,  4, 25, 19])

In [66]:
a = np.arange(12).reshape(2,6)
b = np.arange(12).reshape(2,6)

np.concatenate([a,b], axis = 0)
np.concatenate([a,b], axis = 1)

array([[ 0,  1,  2,  3,  4,  5,  0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11,  6,  7,  8,  9, 10, 11]])

In [70]:
np.concatenate([np.array([[1, 2, 3, 4]]), np.array([[4, 5]])], axis=0)

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 4 and the array at index 1 has size 2

In [77]:
x = np.arange(9.0)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [82]:
np.split(np.arange(9) , [2,4,7])

[array([0, 1]), array([2, 3]), array([4, 5, 6]), array([7, 8])]

In [92]:
np.arange(6)
np.arange(6).reshape(2,1,1,1,3).squeeze()

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
x = np.arange(6)
np.expand_dims(x , axis=1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [99]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
np.roll(x,2)

array([8, 9, 0, 1, 2, 3, 4, 5, 6, 7])

In [105]:
z = np.arange(5)
np.roll(z, 2)

list(zip(z, np.roll(z,2)))

[(0, 3), (1, 4), (2, 0), (3, 1), (4, 2)]

In [107]:
x = np.arange(100).reshape(5,2,10)
x

array([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]],

       [[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
        [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]],

       [[80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
        [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]]])

In [113]:
import numpy as np

# 3차원 배열 생성
a = np.array([[[1, 2, 3], [4, 5, 6]],
              [[7, 8, 9], [10, 11, 12]]])

# 첫 번째 축과 세 번째 축을 스왑
b = np.swapaxes(a, 0, 2)

print("Original shape:", a.shape)
print("Swapped shape:", b.shape)
print(b)

Original shape: (2, 2, 3)
Swapped shape: (3, 2, 2)
[[[ 1  7]
  [ 4 10]]

 [[ 2  8]
  [ 5 11]]

 [[ 3  9]
  [ 6 12]]]


In [119]:
x = np.arange(100).reshape(5, 2, 10)
x.transpose(0, 2, 1).shape   # 1번 축과 2번 축을 바꿈 # 2->0, 0->1, 1->2

(5, 10, 2)

In [125]:
x = np.random.randint(0, 15, (5, 3))
x

array([[ 8,  7,  4],
       [ 0,  1, 14],
       [ 9, 12,  1],
       [ 2,  2, 11],
       [ 3, 13,  2]])

In [127]:
x.sort(axis=1)
x

array([[ 4,  7,  8],
       [ 0,  1, 14],
       [ 1,  9, 12],
       [ 2,  2, 11],
       [ 2,  3, 13]])

In [139]:
x = np.random.randint(1, 6, size=5)
print(x)
x.sort(0)
print(x)
print(x.argsort())

[1 2 3 1 1]
[1 1 1 2 3]
[0 1 2 3 4]


In [144]:
x = np.random.randint(10, size=10)
print(x)
np.unique(x)

[2 4 4 3 5 4 4 4 7 2]


array([2, 3, 4, 5, 7])

In [145]:
x = np.array([3, 2, 1, 4, 5, np.nan, np.nan, 5, 4])
np.nan_to_num(x, nan=100)

array([  3.,   2.,   1.,   4.,   5., 100., 100.,   5.,   4.])

In [151]:
from tqdm import tqdm
x = np.arange(10)
y = np.lib.stride_trics.sliding_widow_view(x,3)

AttributeError: module 'numpy.lib' has no attribute 'stride_trics'

In [178]:
s = int(input())

for i in range(s):
    a,b = map(int , input().split())
    print(a+b)

2
5
7
17
7


In [180]:
s = int(input())
total_sum = 0 

for i in range(1 , s+1):
    total_sum += i
print(total_sum)

6


In [193]:
row , colum = map(int , input().split())

matrix_a = []
for i in range(row):
    a_list = list(map(int , input().split()))
    matrix_a.append(a_list)

print(matrix_a)
matrix_b = []
for i in range(row):
    b_list = list(map(int , input().split()))
    matrix_b.append(b_list)

matrix_a = np.array(matrix_a)
matrix_b = np.array(matrix_b)

result_mx = matrix_a + matrix_b 

for r in result_mx:
    print(' '.join(map(str, r)))

[[1, 1, 1], [2, 2, 2], [0, 1, 0]]


In [208]:
n,m = 3,3

matrix_a = []
for i in range(n):
    a_list = list(map(int,input().split()))
    matrix_a.append(a_list)

In [226]:
matrix_a = []
for i in range(3):
    a_list = list(map(int,input().split()))
    matrix_a.append(a_list)

matrix_a = np.array(matrix_a)

max_index_flat = np.argmax(matrix_a)
row, col = np.unravel_index(max_index_flat, matrix_a.shape)

print(matrix_a.max())
print(row+1, col+1)

7
3 1


In [228]:
print(matrix_a)

[[1 3 3]
 [4 4 5]
 [7 6 7]]


In [231]:
matrix_a = []
for i in range(3):
    a_list = list(map(str,input()))
    matrix_a.append(a_list)

In [243]:
matrix_a = []
for i in range(5):
    a_list = list(map(str,input()))
    matrix_a.append(a_list)
matrix_a = np.array(matrix_a)
matrix_b = matrix_a.transpose()

for rows in matrix_b:
    print(''.join(map(str, rows)) , end="")

In [263]:
matrix_b = matrix_a.transpose()

for rows in matrix_b:
    print(''.join(map(str, rows)) , end="")


qazwsxedcrfvtgb

In [277]:
#학생이 한반에 100명이 있음. 시험을 봤는데 성적이 1~100등까지 나왔음
#19등까지는 1을 주고 싶고 , 20~39는 2를 주고 , 80~99은 5를 받게 하는 프로그램 작성하기 
#그거를 if , for 문 없이  

import numpy as np 
ranks = np.arange(1,100)
np.where(ranks <= 20 , 1, np.where(ranks <= 40, 2 , np.where(ranks <= 60, 3 , np.where(ranks <= 80 , 4 , np.where(ranks <= 100, 5, 5)))))


a = np.arange(1,100)
np.random.shuffle(a)
a = a//20+1
a

array([5, 2, 3, 3, 3, 4, 1, 1, 2, 5, 4, 4, 2, 1, 5, 5, 5, 1, 1, 1, 4, 3,
       2, 4, 2, 1, 5, 1, 5, 1, 2, 3, 5, 5, 4, 1, 1, 3, 2, 3, 5, 2, 2, 1,
       2, 1, 2, 3, 4, 4, 3, 4, 1, 4, 3, 4, 4, 3, 3, 1, 2, 3, 2, 3, 5, 1,
       5, 2, 4, 5, 3, 4, 4, 2, 2, 2, 4, 3, 2, 1, 3, 5, 2, 3, 5, 4, 5, 5,
       3, 4, 3, 2, 1, 5, 1, 4, 4, 5, 5])

In [ ]:
#숫자만 무조건 받게 하기 , 문자열 들어간 거 받으면 다시 입력하도록 해서 무조건 점수 나오게 
#숫자만 무조건 받게 하면 코드 뎁스를 줄일 수 있음 
try:
    score = int(input())
    assert 0 <= int(score) <= 100
    if score >= 90:     # score < 100 and score > 90
        print('A')
    elif score >= 80:   # score < 90 and score >= 80
        print('B')
    elif score >= 70:
        print('C')
    elif score >= 60:
        print('D')
    else:
        print('F')
except TypeError as e:
    print('입력 오류')
except Exception as e:
    print('입력 오류')

In [278]:
row , colum = map(int , input().split())

matrix_a = []
for i in range(row):
    a_list = list(map(int , input().split()))
    matrix_a.append(a_list)

print(matrix_a)
matrix_b = []
for i in range(row):
    b_list = list(map(int , input().split()))
    matrix_b.append(b_list)

matrix_a = np.array(matrix_a)
matrix_b = np.array(matrix_b)

result_mx = matrix_a + matrix_b 

for r in result_mx:
    print(' '.join(map(str, r)))

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
2 4 6
8 10 12
14 16 18


In [280]:
import numpy as np

matrix_a = []
for i in range(9):
    a_list = list(map(int,input().split()))
    matrix_a.append(a_list)

matrix_a = np.array(matrix_a)
matrix_a 

array([[ 3, 23, 85, 34, 17, 74, 25, 52, 65],
       [10,  7, 39, 42, 88, 52, 14, 72, 63],
       [87, 42, 18, 78, 53, 45, 18, 84, 53],
       [34, 28, 64, 85, 12, 16, 75, 36, 55],
       [21, 77, 45, 35, 28, 75, 90, 76,  1],
       [25, 87, 65, 15, 28, 11, 37, 28, 74],
       [65, 27, 75, 41,  7, 89, 78, 64, 39],
       [47, 47, 70, 45, 23, 65,  3, 41, 44],
       [87, 13, 82, 38, 31, 12, 29, 29, 80]])

In [293]:
matrix_a.max()

np.where(matrix_a == matrix_a.max())
row , col = np.where(matrix_a == matrix_a.max())

row.item() + 1 , col.item() + 1 #한 개 있는 배열에서밖에 못 들고 옴 

ValueError: can only convert an array of size 1 to a Python scalar

In [1]:
#숫자만 무조건 받게 하기 , 문자열 들어간 거 받으면 다시 입력하도록 해서 무조건 점수 나오게 
#숫자만 무조건 받게 하면 코드 뎁스를 줄일 수 있음 
try:
    score = int(input())
    assert 0 <= int(score) <= 100
    if score >= 90:     # score < 100 and score > 90
        print('A')
    elif score >= 80:   # score < 90 and score >= 80
        print('B')
    elif score >= 70:
        print('C')
    elif score >= 60:
        print('D')
    else:
        print('F')
except TypeError as e:
    print('입력 오류')
except Exception as e:
    print('입력 오류')

입력 오류


In [3]:
while True:
    try:
        score = int(input())
        assert 0 <= score <= 100 
        if score >= 90:
            print('A')
        elif score >= 80:
            print('B')
        elif score >= 70:
            print('C')
        elif score >= 60:
            print('D')
        break
    except AssertionError as e:
        print('다시 입력하세요')
    except ValueError as e:
        print('다시 입력하세요')


다시 입려하세요
다시 입력하세요
다시 입력하세요
A


In [ ]:
while True:
    try:
        score = int(input())
        assert 0 <= score <= 100
    except AssertionError as e:
        print('다시 입력하세요')
    except ValueError as e:
        print('다시 입력하세요')
    else:
        break 

if score >= 90:
    print('A')
elif score >= 80:
    print('B')
elif score >= 70:
    print('C')
elif score >= 60:
    print('D')

In [4]:
import pandas as pd

In [7]:
health_data = pd.read_csv('국민건강보험공단_건강검진정보_20221231.CSV' , encoding='cp949')

In [17]:
health_data.isna().sum() / len(health_data) * 100 

#내림차순 기준으로 퍼센트를 정렬해오셈

기준년도            0.0000
가입자일련번호         0.0000
시도코드            0.0000
성별              0.0000
연령대코드(5세단위)     0.0000
신장(5cm단위)       0.0000
체중(5kg단위)       0.0000
허리둘레            0.0392
시력(좌)           0.0186
시력(우)           0.0185
청력(좌)           0.0115
청력(우)           0.0116
수축기혈압           0.5556
이완기혈압           0.5556
식전혈당(공복혈당)      0.5611
총콜레스테롤         65.4382
트리글리세라이드       65.4386
HDL콜레스테롤       65.4386
LDL콜레스테롤       66.0926
혈색소             0.5616
요단백             1.1054
혈청크레아티닌         0.5615
혈청지오티(AST)      0.5613
혈청지피티(ALT)      0.5613
감마지티피           0.5611
흡연상태            0.0096
음주여부            0.0073
구강검진수검여부        0.0000
치아우식증유무        65.5671
치석             65.5670
dtype: float64

In [15]:
health_data.shape

(1000000, 30)

In [16]:
len(health_data)

1000000

In [ ]:
로그로 변형된 & 대륙별로 색깔을 변형해서 가져올 것